files: '(src/.*)|(tests/.*)|(tests_helpers/.*)|(^examples/.*)|(docs/examples/tutorial/.*)'
default_stages:
  - commit
  - push

repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=100']

  - repo: 'https://github.com/myint/eradicate'
    rev: v2.1.0
    hooks:
      - id: eradicate
        args: ['-e']  # remove default --in-place argument and emit error

  - repo: 'https://github.com/pycqa/isort'
    rev: 5.12.0
    hooks:
      - id: isort
