dist: bionic
language: python
python:
  - "3.10"
  - "3.9"
  - "3.8"
  - "3.7"
script:
  nose2 -v && mypy tests dataclass_factory
install:
  - pip3 install -r requirements.txt
  - mypy --install-types
