[build-system]
requires = ["wheel", "setuptools"]
build-backend = "setuptools.build_meta"


[tool.isort]
multi_line_output = 3
line_length = 120
include_trailing_comma = true
combine_as_imports = true
remove_redundant_aliases = true

[tool.pytest.ini_options]
python_classes = 'WeDoNotUseClassTestCase'
testpaths = 'tests_30'
filterwarnings = ['ignore::dataclass_factory_30.model_tools.introspection.TypedDictAt38Warning']

[tool.bandit]
skips = ['B102']

[tool.vulture]
min_confidence = 60
ignore_decorators = ['@_aspect_storage.add', '@overload', '@abstractmethod']
