name: Run linters and tests

on:
  push:
    branches-ignore:
      - "2.x/*"
  pull_request:
    branches-ignore:
      - "2.x/*"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Just
        uses: extractions/setup-just@v1
        with:
          just-version: 1.14.0

      - name: Setup environment to run tox
        run:
          just setup-runner

      - name: Run linters
        run:
          just lint

  testing:
    name: Testing
    runs-on: ${{ matrix.os }}
    needs: linting

    strategy:
      fail-fast: true
      matrix:
        python_version:
          - { setup: '3.8',      tox: 'py38'    }
          - { setup: '3.9',      tox: 'py39'    }
          - { setup: '3.10',     tox: 'py310'   }
          - { setup: '3.11',     tox: 'py311'   }
          - { setup: '3.12',     tox: 'py312'   }
          - { setup: 'pypy3.8',  tox: 'pypy38'  }
          - { setup: 'pypy3.9',  tox: 'pypy39'  }
          - { setup: 'pypy3.10', tox: 'pypy310' }

        os: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version.setup }}

      - name: Install Just
        uses: extractions/setup-just@v1
        with:
          just-version: 1.14.0

      - name: Setup environment to run tox
        run:
          just setup-runner

      - name: Run tests
        run:
          just test-with-coverage ${{ matrix.python_version.tox }}

      - name: Store coverage file
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python_version.setup }}
          path: coverage.db
          if-no-files-found: error

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: testing
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        id: download
        with:
          pattern: coverage-*
          merge-multiple: true

      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_COVERAGE_FILES: true

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v4
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt
