name: Run tests

on:
  push:
    branches:
      - "3.x/*"
  pull_request:
    branches:
      - "3.x/*"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    name: Run linters
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Just
        uses: extractions/setup-just@v1
        with:
          just-version: 1.14.0

      - name: Setup environment to run tox
        run:
          just setup-runner

      - name: Run linters
        run:
          just lint

  testing:
    name: Run tests
    runs-on: ${{ matrix.os }}
    needs: linting

    strategy:
      fail-fast: true
      matrix:
        python_version:
          - { setup: '3.8',      tox: 'py38'    }
          - { setup: '3.9',      tox: 'py39'    }
          - { setup: '3.10',     tox: 'py310'   }
          - { setup: '3.11',     tox: 'py311'   }
          - { setup: 'pypy3.8',  tox: 'pypy38'  }
          - { setup: 'pypy3.9',  tox: 'pypy39'  }
          - { setup: 'pypy3.10', tox: 'pypy310' }

        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version.setup }}

      - name: Install Just
        uses: extractions/setup-just@v1
        with:
          just-version: 1.14.0

      - name: Setup environment to run tox
        run:
          just setup-runner

      - name: Run tests
        run:
          just test-on-python-version ${{ matrix.python_version.tox }}
