# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@develop
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: -r dataclass_factory tests

      - name: Run Isort
        run: |
          python -m isort dataclass_factory tests

      - name: Run flake8
        run: |
          python -m flake8 dataclass_factory tests --count --exit-zero --statistics --show-source

      - name: Run vulture
        run: |
          poetry run vulture dataclass_factory

      - name: Run Mypy
        run: |
          python -m mypy dataclass_factory

      - name: Run tests
        run: |
          python -m nose2 -B -C tests
