# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  cpython:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@develop
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8
        run: |
          python -m flake8 dataclass_factory tests --count --exit-zero --statistics --show-source

      - name: Run vulture
        run: |
          python -m vulture dataclass_factory tests

      - name: Run Mypy
        run: |
          python -m mypy dataclass_factory tests

      - name: Run tests
        run: |
          python -m nose2 -B -C tests
          
  pypy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        pypy-version: ['pypy3']

    steps:
    - uses: actions/checkout@develop
    - name: Install Pypy
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.pypy-version }}

    - name: Install dependencies
      run: |
          pypy -m ensurepip
          pypy -mpip install -U pip
          pypy -mpip install nose2

    - name: Run tests
      run: |
          nose2 -B -C tests
    
