name: Run tests on all operating systems

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  testing:
    name: Run tests
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - { setup: '3.8',      tox: 'py38'    }
          - { setup: '3.9',      tox: 'py39'    }
          - { setup: '3.10',     tox: 'py310'   }
          - { setup: '3.11',     tox: 'py311'   }
          - { setup: '3.12',     tox: 'py312'   }
          - { setup: 'pypy3.8',  tox: 'pypy38'  }
          - { setup: 'pypy3.9',  tox: 'pypy39'  }
          - { setup: 'pypy3.10', tox: 'pypy310' }

        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version.setup }}

      - name: Install Just
        uses: extractions/setup-just@v1
        with:
          just-version: 1.14.0

      - name: Setup environment to run tox
        run:
          just setup-runner

      - name: Run tests
        run:
          just test-on ${{ matrix.python_version.tox }}
